const phones = [
  {
    "id": "apple-iphone-11-128gb-black",
    "category": "phones",
    "namespaceId": "apple-iphone-11",
    "name": "Apple iPhone 11 128GB Black",
    "capacityAvailable": ["64GB", "128GB", "256GB"],
    "capacity": "128GB",
    "priceRegular": 1100,
    "priceDiscount": 1050,
    "colorsAvailable": ["black", "green", "yellow", "white", "purple", "red"],
    "color": "black",
  },
  {
    "id": "apple-iphone-11-128gb-green",
    "category": "phones",
    "namespaceId": "apple-iphone-11",
    "name": "Apple iPhone 11 128GB Green",
    "capacityAvailable": ["64GB", "128GB", "256GB"],
    "capacity": "128GB",
    "priceRegular": 1100,
    "priceDiscount": 1050,
    "colorsAvailable": ["black", "green", "yellow", "white", "purple", "red"],
    "color": "green",
  },
  {
    "id": "apple-iphone-11-128gb-purple",
    "category": "phones",
    "namespaceId": "apple-iphone-11",
    "name": "Apple iPhone 11 128GB Purple",
    "capacityAvailable": ["64GB", "128GB", "256GB"],
    "capacity": "128GB",
    "priceRegular": 1100,
    "priceDiscount": 1050,
    "colorsAvailable": ["black", "green", "yellow", "white", "purple", "red"],
    "color": "purple",
  }
]

const phoneDetails = [
  {
    screen: "6.1' IPS",
    resolution: '1792x828',
    processor: 'Apple A13 Bionic',
    ram: '4GB',
    camera: '12 Mp + 12 Mp + 12MP',
    zoom: 'Digital, 5x',
    cell: ['GPRS', 'EDGE', 'WCDMA', 'UMTS', 'HSPA', 'LTE'],
  },
  {
    screen: "6.1' IPS",
    resolution: '1792x828',
    processor: 'Apple A13 Bionic',
    ram: '4GB',
    camera: '12 Mp + 12 Mp + 12MP',
    zoom: 'Digital, 5x',
    cell: ['GPRS', 'EDGE', 'WCDMA', 'UMTS', 'HSPA', 'LTE'],
  },
  {
    screen: "6.1' IPS",
    resolution: '1792x828',
    processor: 'Apple A13 Bionic',
    ram: '4GB',
    camera: '12 Mp + 12 Mp + 12MP',
    zoom: 'Digital, 5x',
    cell: ['GPRS', 'EDGE', 'WCDMA', 'UMTS', 'HSPA', 'LTE'],
  },
];

const tablets = [
  {
    id: 'apple-ipad-pro-11-2021-128gb-spacegray',
    category: 'tablets',
    namespaceId: 'apple-ipad-pro-11-2021',
    name: 'Apple iPad Pro 11 (2021) 128GB Space Gray',
    capacityAvailable: ['128GB', '256GB', '512GB', '1TB', '2TB'],
    capacity: '128GB',
    priceRegular: 799,
    priceDiscount: 749,
    colorsAvailable: ['spacegray', 'silver'],
    color: 'spacegray',
  },
  {
    id: 'apple-ipad-pro-11-2021-256gb-spacegray',
    category: 'tablets',
    namespaceId: 'apple-ipad-pro-11-2021',
    name: 'Apple iPad Pro 11 (2021) 256GB Space Gray',
    capacityAvailable: ['128GB', '256GB', '512GB', '1TB', '2TB'],
    capacity: '256GB',
    priceRegular: 829,
    priceDiscount: 799,
    colorsAvailable: ['spacegray', 'silver'],
    color: 'spacegray',
  },
  {
    id: 'apple-ipad-pro-11-2021-512gb-spacegray',
    category: 'tablets',
    namespaceId: 'apple-ipad-pro-11-2021',
    name: 'Apple iPad Pro 11 (2021) 512GB Space Gray',
    capacityAvailable: ['128GB', '256GB', '512GB', '1TB', '2TB'],
    capacity: '512GB',
    priceRegular: 869,
    priceDiscount: 819,
    colorsAvailable: ['spacegray', 'silver'],
    color: 'spacegray',
  },
];

const tabletsDetails = [
  {
    screen: "11' Liquid Retina",
    resolution: '2388x1668',
    processor: 'Apple M1',
    ram: '8GB',
    camera: '12MP + 12MP',
    zoom: 'Digital zoom up to 5x',
    cell: ['Not applicable'],
  },
  {
    screen: "11' Liquid Retina",
    resolution: '2388x1668',
    processor: 'Apple M1',
    ram: '8GB',
    camera: '12MP + 12MP',
    zoom: 'Digital zoom up to 5x',
    cell: ['Not applicable'],
  },
  {
    screen: "11' Liquid Retina",
    resolution: '2388x1668',
    processor: 'Apple M1',
    ram: '8GB',
    camera: '12MP + 12MP',
    zoom: 'Digital zoom up to 5x',
    cell: ['Not applicable'],
  },
];

const accessories = [
  {
    id: 'apple-watch-series-3-38mm-space-gray',
    category: 'accessories',
    namespaceId: 'apple-watch-series-3',
    name: 'Apple Watch Series 3 38mm Space Gray',
    capacityAvailable: ['38mm', '42mm'],
    capacity: '38mm',
    priceRegular: 199,
    priceDiscount: 169,
    colorsAvailable: [' gray', 'silver', 'gold'],
    color: 'space gray',
  },
  {
    id: 'apple-watch-series-3-42mm-space-gray',
    category: 'accessories',
    namespaceId: 'apple-watch-series-3',
    name: 'Apple Watch Series 3 42mm Space Gray',
    capacityAvailable: ['38mm', '42mm'],
    capacity: '42mm',
    priceRegular: 250,
    priceDiscount: 219,
    colorsAvailable: ['space gray', 'silver', 'gold'],
    color: 'space gray',
  },
  {
    id: 'apple-watch-series-3-38mm-gold',
    category: 'accessories',
    namespaceId: 'apple-watch-series-3',
    name: 'Apple Watch Series 3 38mm Gold',
    capacityAvailable: ['38mm', '42mm'],
    capacity: '38mm',
    priceRegular: 199,
    priceDiscount: 169,
    colorsAvailable: ['space gray', 'silver', 'gold'],
    color: 'gold',
  },
];

const accessoriesDetails = [
  {
    screen: "1.3' OLED",
    resolution: '272x340',
    processor: 'Apple S3',
    ram: '768MB',
    cell: ['Wi-Fi', 'Bluetooth', 'LTE'],
  },
  {
    screen: "1.3' OLED",
    resolution: '272x340',
    processor: 'Apple S3',
    ram: '768MB',
    cell: ['Wi-Fi', 'Bluetooth', 'LTE'],
  },
  {
    screen: "1.3' OLED",
    resolution: '272x340',
    processor: 'Apple S3',
    ram: '768MB',
    cell: ['Wi-Fi', 'Bluetooth', 'LTE'],
  },
];